#!/usr/bin/env node
/**
 * Zero-external-origin scan.
 *
 * The console has to work with the network off and must not leak a single
 * request. Anything that could reach an outside origin is a failure, including
 * a CDN font, an analytics beacon, or a remote image.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, extname } from 'node:path'

const PATTERNS = [
  { re: /https?:\/\/(?!localhost|127\.0\.0\.1)/g, what: 'remote URL' },
  { re: /\bfetch\s*\(/g, what: 'fetch()' },
  { re: /XMLHttpRequest/g, what: 'XMLHttpRequest' },
  { re: /navigator\.sendBeacon/g, what: 'sendBeacon' },
  { re: /new\s+WebSocket/g, what: 'WebSocket' },
  { re: /new\s+EventSource/g, what: 'EventSource' },
  { re: /@import\s+url\(/g, what: 'CSS remote import' },
]

const EXTS = new Set(['.ts', '.tsx', '.css', '.html'])
const EXEMPT = ['check-network.mjs']

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === '.git' || name === 'dist') continue
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path, out)
    else if (EXTS.has(extname(path))) out.push(path)
  }
  return out
}

const scanned = []
const findings = []
for (const file of walk('.')) {
  if (EXEMPT.some((e) => file.endsWith(e))) continue
  scanned.push(file)
  readFileSync(file, 'utf8').split('\n').forEach((text, i) => {
    if (text.trimStart().startsWith('*') || text.trimStart().startsWith('//')) return
    for (const p of PATTERNS) {
      p.re.lastIndex = 0
      if (p.re.test(text)) findings.push({ file, line: i + 1, what: p.what, text: text.trim() })
    }
  })
}

// The result is written out, not just printed, so module 05 can render a
// count it did not invent. A number typed into a seed file is a claim; a
// number read from this scan is a measurement.
writeFileSync(
  'seed/network-scan.json',
  JSON.stringify(
    {
      _note:
        'Generated by scripts/check-network.mjs. Do not hand-edit — the whole point of this file is that nobody typed the number in it.',
      patterns: PATTERNS.map((p) => p.what),
      filesScanned: scanned.length,
      externalRequests: findings.length,
      findings: findings.map((f) => ({ file: f.file, line: f.line, what: f.what })),
    },
    null,
    2,
  ) + '\n',
)

if (findings.length === 0) {
  console.log(
    `External origins: none across ${scanned.length} files. Runs offline.`,
  )
  process.exit(0)
}

console.error(`External origins: ${findings.length} finding(s).\n`)
for (const f of findings) {
  console.error(`  ${f.file}:${f.line}  ${f.what}`)
  console.error(`    ${f.text}\n`)
}
process.exit(1)
